#application url
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

# browser configuration
browser = chrome

#credentials
username = admin
password = admin123

#ImplicitWait (in seconds)
implicitWait = 10

# Explicit wait
explicitWait = 30
